---
####

- name: SNAPSHOT VM - DELETE
  uri:
    url: "https://{{ proxmox_api_host }}/api2/json/nodes/{{ proxmox_node }}/qemu/{{ proxmox_vmid }}/snapshot/{{ proxmox_snapshot_to_delete }}"
    method: DELETE
    headers:
      Authorization: "PVEAPIToken={{ proxmox_api_user }}!{{ proxmox_api_token_id }}={{ proxmox_api_token_secret }}"
    validate_certs: no
  register: snapshot_delete_output
  when: proxmox_vm_action == "snapshot_delete"

- debug: var=snapshot_delete_output
  when: proxmox_vm_action == "snapshot_delete"
