---
####

- name: VM PAUSE
  uri:
    url: "https://{{ proxmox_api_host }}/api2/json/nodes/{{ proxmox_node }}/qemu/{{ proxmox_vmid }}/status/suspend"
    method: POST
    headers:
      Authorization: "PVEAPIToken={{ proxmox_api_user }}!{{ proxmox_api_token_id }}={{ proxmox_api_token_secret }}"
    validate_certs: no
  register: vm_pause_output
  when: proxmox_vm_action == "vm_pause"

- debug: var=vm_pause_output
  when: proxmox_vm_action == "vm_pause"

- name: VM PAUSE - FETCH STATUS
  uri:
    url: "https://{{ proxmox_api_host }}/api2/json/nodes/{{ proxmox_node }}/qemu/{{ proxmox_vmid }}/status/current"
    method: GET
    headers:
      Authorization: "PVEAPIToken={{ proxmox_api_user }}!{{ proxmox_api_token_id }}={{ proxmox_api_token_secret }}"
    validate_certs: no
  register: vm_info
  when: proxmox_vm_action == "vm_pause"

- name: VM PAUSE - BUILD JSON
  set_fact:
    vm_pause:
      vm_id: "{{ proxmox_vmid }}"
      vm_name: "{{ vm_info.json.data.name }}"
      vm_status: "{{ vm_info.json.data.status }}"
      action: "vm_pause"
      # raw_info: "{{ vm_info.json }}" # orig json proxmox
  when: proxmox_vm_action == "vm_pause"

- name: VM STOP - SHOW JSON
  debug:
    var: vm_pause
  when: proxmox_vm_action == "vm_pause"
