---
##
## #PR-5
##

- block:
    ####
    ####

    - name: VM - CREATE
      uri:
        url: "https://{{ proxmox_api_host }}/api2/json/nodes/{{ proxmox_node }}/qemu"
        method: POST
        headers:
          Authorization: "PVEAPIToken={{ proxmox_api_user }}!{{ proxmox_api_token_id }}={{ proxmox_api_token_secret }}"
        body_format: form-urlencoded
        body:
          action: "vm_create"
          source: "proxmox"
          proxmox_node: "{{ proxmox_node }}"
          #
          vmid: "{{ proxmox_new_vm.vmid }}"
          name: "{{ proxmox_new_vm.name }}"
          cpu: "{{ proxmox_new_vm.cpu }}"
          cores: "{{ proxmox_new_vm.cores }}"
          sockets: "{{ proxmox_new_vm.sockets }}"
          memory: "{{ proxmox_new_vm.memory }}"
          balloon: 0
          scsi0: "local-lvm:{{ proxmox_new_vm.disk_size }},format=raw"
          ide2: "{{ proxmox_new_vm.iso }},media=cdrom"
          net0: "virtio,bridge=vmbr0"
          boot: "order=ide2"
        validate_certs: no
      register: vm_create_output

    - name: VM _CREATE - PRINT proxmox_call
      debug:
        var: vm_create_output

    ####
    ####

  ####
  ####

  when: proxmox_vm_action == "vm_create"
