---
##
##
##

- block:
    ####
    ####

    - name: NETWORK - VM - GET - CDROM STATUS
      vars:
        proxmox_vmid: 100 # TODO - OVERWRITED_ARGUMENTS

      uri:
        url: "https://{{ proxmox_api_host }}/api2/json/nodes/{{ proxmox_node }}/qemu/{{ proxmox_vmid }}/config"
        method: GET
        headers:
          Authorization: "PVEAPIToken={{ proxmox_api_user }}!{{ proxmox_api_token_id }}={{ proxmox_api_token_secret }}"
        validate_certs: no
      register: proxmox_call_vm_config_is_iso_mount_in_cdrom

    ####
    ####

    # - name: RETURN ONLY TASK OUTPUT - proxmox_call_vm_config_is_iso_mount_in_cdrom
    #   debug:
    #     var: proxmox_call_vm_config_is_iso_mount_in_cdrom

    - name: RETURN ONLY TASK OUTPUT - proxmox_call_network_vm_list_int
      shell: |
        echo "{{ proxmox_call_vm_config_is_iso_mount_in_cdrom.json.data | 
          to_nice_yaml }}" |
          grep "media=cdrom"
      register: proxmox_call__shell_pipe__cdrom_status

    - debug: var=proxmox_call__shell_pipe__cdrom_status.stdout_lines

  ####
  ####

  when: proxmox_vm_action == "vm_get_config_cdrom"
