---
##
## #PR-11
##

- block:
    ####
    ####

    - name: VM LIST
      uri:
        url: "https://{{ proxmox_api_host }}/api2/json/nodes/{{ proxmox_node }}/qemu"
        headers:
          Authorization: "PVEAPIToken={{ proxmox_api_user }}!{{ proxmox_api_token_id }}={{ proxmox_api_token_secret }}"
        return_content: true
        validate_certs: no
      register: proxmox_call

    ####
    ####

    - name: VM LIST - PRINT proxmox_call
      debug:
        var: proxmox_call

    - name: VM LIST - BUILD JSON
      set_fact:
        vm_list: >- #
          {{ (vm_list | default([])) +
            [ {
              'action': "vm_list",
              'source': "proxmox",
              'proxmox_node':   proxmox_node ,
              
              'vm_name':    (item.name    | default('?')),
              'vm_status':  (item.status  | default('?')),
              'vm_id':      (item.vmid    | default('?')),
              'vm_uptime':  (item.uptime  | default('?')),
              
              'vm_meta': {
                'cpu_current_usage':  (item.cpu       | default('?')),
                'cpu_allocated':      (item.cpus      | default('?')),
                'disk_current_usage': (item.disk      | default('?')),
                'disk_read':          (item.diskread  | default('?')),
                'disk_write':         (item.diskwrite | default('?')),
                'disk_max':           (item.maxdisk   | default('?')),
                'ram_current_usage':  (item.mem       | default('?')),
                'ram_max':            (item.maxmem    | default('?')),
                'net_in':             (item.netin     | default('?')),
                'net_out':            (item.netout    | default('?'))
              }
            } ] }}
      loop: "{{ proxmox_call.json.data }}"

    - name: VM LIST - PRINT JSON
      debug:
        var: vm_list

  ####
  ####

  when: proxmox_vm_action == "vm_list"
