---
##
## ISSUE - 82
##

# import-file bugged / not fully implemented ?
#
# https://forum.proxmox.com/threads/workaround-how-to-refer-via-api-to-a-downloaded-image-file-stored-in-the-images-folder.161477/
# https://forum.proxmox.com/threads/new-vm-from-cloud-init-image-via-api.111091/#post-482517
# https://lore.proxmox.com/all/20250408121312.312526-1-d.csapak@proxmox.com/
# https://bugzilla.proxmox.com/show_bug.cgi?id=2424

- block:
    - name: CLOUD INIT - INJECT VARIABLE
      uri:
        url: "https://{{ proxmox_api_host }}/api2/json/nodes/{{ proxmox_node }}/qemu/{{ vm_id }}/config"
        method: PUT
        headers:
          Authorization: "PVEAPIToken={{ proxmox_api_user }}!{{ proxmox_api_token_id }}={{ proxmox_api_token_secret }}"
        validate_certs: no
        body_format: form-urlencoded
        body:
          ciuser: "{{ vm_ci_user | default(omit)  }}"
          cipassword: "{{ vm_ci_password | default(omit)  }}"
#          sshkeys: "{{ vm_ci_ssh_key | urlencode | default(omit)  }}"
#          sshkeys: "{{ vm_ci_ssh_key | replace('/', '%2F') | urlencode | default(omit) }}"
          sshkeys: "{{ vm_ci_ssh_key | trim | urlencode | replace('/', '%2F') }}"
#          sshkeys: "{{ vm_ci_ssh_key | trim | urlencode | replace('/', '2%F') |   default(omit) }}"

          searchdomain: "{{ vm_ci_dns_domain | default(omit)  }}"
          nameserver: "{{ vm_ci_dns_ips | default(omit)  }}" # format :  1.1.1.1,2.2.2.2

          ipconfig0: >-
            {% if vm_ci_ip is defined %}ip={{ vm_ci_ip }}/{{ vm_ci_netmask }}{% if vm_ci_ip_gw is defined %},gw={{ vm_ci_ip_gw }}{% endif %}{% else %}{{ omit }}{% endif %}
          # ipconfig0: >-
          #   {% if vm_ci_ip is defined %}
          #     ip={{ vm_ci_ip }}/{{ vm_ci_netmask }}
          #       {% if vm_ci_ip_gw is defined %},
          #         gw={{ vm_ci_ip_gw }}
          #       {% endif %}
          #   {% else %}
          #     {{ omit }}
          #   {% endif %}
          # ip6config0: "ip6=fd00::2/64,gw6=fd00::1" # format :  "ip6=fd00::2/64,gw6=fd00::1"

      register: proxmox_call

    - name: CLOUD INIT - INJECT VARIABLE
      debug:
        var: proxmox_call

    ####
    ####
    ####

    - name: CLOUD INIT - REGEN TEMPLATE
      uri:
        url: "https://{{ proxmox_api_host }}/api2/json/nodes/{{ proxmox_node }}/qemu/{{ vm_id }}/cloudinit"
        method: PUT
        headers:
          Authorization: "PVEAPIToken={{ proxmox_api_user }}!{{ proxmox_api_token_id }}={{ proxmox_api_token_secret }}"
        validate_certs: no
        body_format: raw
        body: ""
      register: proxmox_call

    - name: TEMPLATE - CONVERT VM TO TEMPLATE PRINT JSON
      debug:
        var: proxmox_call

    ####
    ####
    ####

    - name: CLOUD INIT - BUILD JSON
      set_fact:
        cloudinit_set_variables:
          action: "cloudinit_set_variables"
          source: "proxmox"
          proxmox_node: "{{ proxmox_node }}"
          vm_id: "{{ vm_id | int }}"
          template_status: "regenerated"

          ciuser: "{{ vm_ci_user | default(omit)  }}"
          cipassword: "{{ 'redacted' | default(omit)  }}"
          sshkeys: "{{ 'redacted' | default(omit)  }}"
          vm_ci_ip: "{{ vm_ci_ip | default(omit)  }}"
          vm_ci_ip_gw: "{{ vm_ci_ip_gw | default(omit)  }}"
          vm_ci_netmask: "{{ vm_ci_netmask | default(omit)  }}"
          vm_ci_dns_domain: "{{ vm_ci_dns_domain | default(omit)  }}"
          vm_ci_dns_ips: "{{ vm_ci_dns_ips | default(omit)  }}"

    - name: CLOUD INIT - PRINT JSON
      debug:
        var: cloudinit_set_variables

  # when: proxmox_vm_action == "cloudinit_set_variables"
  when: proxmox_vm_action in ["cloudinit_set_variables", "template_create"]
  
