---
##
##
##

- block:
    ####
    ####

    - name: STORAGE - LIST ISO
      vars:
        proxmox_storage: "local" # TODO - OVERWRITED_ARGUMENTS
      uri:
        url: "https://{{ proxmox_api_host }}/api2/json/nodes/{{ proxmox_node }}/storage/{{ proxmox_storage }}/content?content=iso"
        # url: "https://{{ proxmox_api_host }}/api2/json/nodes/{{ proxmox_node }}/storage/local/content?content=iso"
        method: GET
        headers:
          Authorization: "PVEAPIToken={{ proxmox_api_user }}!{{ proxmox_api_token_id }}={{ proxmox_api_token_secret }}"
        validate_certs: no
      register: proxmox_call_list_iso

    ####
    ####

    - name: RETURN ONLY TASK OUTPUT - proxmox_call_list_iso
      debug:
        var: proxmox_call_list_iso

  ####
  ####

  when: proxmox_vm_action == "storage_list_iso"
