---
##
## ISSUE - 74
##

- block:
    ####
    ####

    - name: Download -  ISO
      uri:
        url: "https://{{ proxmox_api_host }}/api2/json/nodes/{{ proxmox_node }}/storage/{{ proxmox_storage }}/download-url"
        method: POST
        headers:
          Authorization: "PVEAPIToken={{ proxmox_api_user }}!{{ proxmox_api_token_id }}={{ proxmox_api_token_secret }}"
        validate_certs: no
        body_format: form-urlencoded
        body:
          content: "{{   iso_file_content_type }}"
          filename: "{{  iso_file_name }}"
          url: "{{       iso_url }}"
          storage: "{{   proxmox_storage }}"
          node: "{{      proxmox_node }}"
          # full: 1
      register: proxmox_call

    ####
    ####
    - name: STORAGE - DOWNLOAD ISO - PRINT proxmox_call
      debug:
        var: proxmox_call

    - name: STORAGE - DOWNLOAD ISO - PRINT proxmox_call
      debug:
        var: proxmox_call

    - name: STORAGE - DOWNLOAD ISO- BUILD JSON
      set_fact:
        storage_download_iso:
          action: "storage_download_iso"
          source: "proxmox"
          proxmox_node: "{{ proxmox_node }}"
          proxmox_storage: "{{ proxmox_storage }}"

          iso_file_content_type: "{{ iso_file_content_type }}"
          iso_file_name: "{{         iso_file_name }}"
          iso_url: "{{               iso_url }}"

          raw_info: "{{ proxmox_call.json }}" # orig json proxmox

    - name: STORAGE - DOWNLOAD ISO - PRINT JSON
      debug:
        var: storage_download_iso

  ####

  vars:
    # proxmox_storage: "local" # TODO - OVERWRITED_ARGUMENTS

  ####

  when: proxmox_vm_action == "storage_download_iso"
