---
##
## #PR-17
##

- block:
    ####
    ####

    - name: STORAGE - LIST STORAGE
      uri:
        url: "https://{{ proxmox_api_host }}/api2/json/nodes/{{ proxmox_node }}/storage"
        method: GET
        headers:
          Authorization: "PVEAPIToken={{ proxmox_api_user }}!{{ proxmox_api_token_id }}={{ proxmox_api_token_secret }}"
        validate_certs: no
      register: proxmox_call

    ####
    ####

    - name: SOTRAGE - LIST STORAGE - PRINT proxmox_call
      debug:
        var: proxmox_call

    ####
    ####

    - name: STORAGE - LIST STORAGE - BUILD JSON
      set_fact:
        storage_list: >-
          {{ (storage_list | default([])) +
            [{
              'action'      : "storage_list",
              'source'      : "proxmox",
              'proxmox_node': proxmox_node,
              
              'storage_name'       :  (item.storage | default("?")),
              'storage_type'       :  (item.type    | default("?")),
              'storage_active'     :  (item.active  | default(-1)),

              'storage_space_available'    :   (item.avail  | default(-1)),
              'storage_space_total'        :   (item.total  | default(-1)),
              'storage_space_used'         :   (item.used   | default(-1)),
              'storage_space_used_fraction':   (item.used_fraction  | default(-1)),

              'storage_content_types' :   (item.content | default(-1)),
              'storage_is_enable'     :   (item.enabled | default(-1)),
              'storage_is_share'      :   (item.shared  | default(-1)),
            }]
          }}
      loop: "{{ proxmox_call.json.data }}"

    - name: STORAGE - LIST STORAGE - PRINT JSON
      debug:
        var: storage_list

  ####

  # vars:
  #   proxmox_storage: "local" # TODO - OVERWRITED_ARGUMENTS

  ####

  when: proxmox_vm_action == "storage_list"
