---
##
## ISSUE - 80
##


- block:
    ####
    ####

    - name: NETWORK - VM - LIST NETWORK INTERFACES
      uri:
        url: "https://{{ proxmox_api_host }}/api2/json/nodes/{{ proxmox_node }}/qemu/{{ vm_id }}/config"
        method: GET
        headers:
          Authorization: "PVEAPIToken={{ proxmox_api_user }}!{{ proxmox_api_token_id }}={{ proxmox_api_token_secret }}"
        validate_certs: no
      register: proxmox_call

    ####
    ####

    - name: NETWORK - VM - LIST NETWORK INTERFACES - proxmox_call
      debug:
        var: proxmox_call

    - name: NETWORK - VM - LIST NETWORK INTERFACES - BUILD JSON
      set_fact:
        network_list_interfaces_vm: >-
          {{ (network_list_interfaces_vm | default([])) +
            [ {
                'action': "network_list_interfaces_vm",
                'source': "proxmox",
                'proxmox_node': proxmox_node,
                'vm_id': vm_id,
                'vm_network_device'  : item.key,
                'vm_network_type'    : item.value.split(',')[0].split('=',1)[0],
                'vm_network_mac'     : item.value.split(',')[0].split('=',1)[1],
                'vm_network_bridge'  : item.value.split(',')[1].split('=',1)[1],
                'vm_network_firewall': (
                  (item.value.split(',')[2].split('=',1)[1])
                  if (item.value is defined and (item.value.split(',')|length) > 2 and '=' in item.value.split(',')[2])
                  else omit
                )
            } ]
          }}
      loop: "{{ proxmox_call.json.data | dict2items }}"
      loop_control:
        label: "{{ item.key }}"
      when: item.key is match('^net[0-9]+$')

    - name: NETWORK - VM - LIST NETWORK INTERFACES - PRINT JSON
      debug:
        var: network_list_interfaces_vm
      when:
        - network_list_interfaces_vm is defined
        - network_list_interfaces_vm | length > 0

  when: proxmox_vm_action == "network_list_interfaces_vm"

  ####
  ####

  # vars:
  #   proxmox_vmid: 100 # TODO - OVERWRITED_ARGUMENTS
