---
##
## PR-20
##
- block:
    ####
    ####

    - name: SNAPSHOT VM - DELETE
      uri:
        url: "https://{{ proxmox_api_host }}/api2/json/nodes/{{ proxmox_node }}/qemu/{{ vm_id }}/snapshot/{{ vm_snapshot_name }}"
        method: DELETE
        headers:
          Authorization: "PVEAPIToken={{ proxmox_api_user }}!{{ proxmox_api_token_id }}={{ proxmox_api_token_secret }}"
        # body_format: json
        # body:

        validate_certs: no
      register: proxmox_call

    ####
    ####

    - name: SNAPSHOT VM - DELETE - PRINT proxmox_call
      debug:
        var: proxmox_call

    - name: SNAPSHOT VM - BUILD JSON
      set_fact:
        snapshot_vm_delete:
          action: "snapshot_vm_delete"
          source: "proxmox"
          proxmox_node: "{{ proxmox_node }}"
          #
          vm_id: "{{ vm_id | int }}"
          vm_name: "{{ vm_name }}"
          vm_snapshot_name: "{{ vm_snapshot_name }}"

          raw_data: "{{ proxmox_call.json }}"

    - name: SNAPSHOT DELETE - PRINT JSON
      debug:
        var: snapshot_vm_delete

  ####
  ####

  when: proxmox_vm_action == "snapshot_vm_delete"
