---
##
##
##

- block:
    ####
    ####

    - name: NODE LEVEL - ENABLE FIREWALL
      uri:
        url: "https://{{ proxmox_api_host }}/api2/json/nodes/{{ proxmox_node }}/firewall/options"
        method: PUT
        headers:
          Authorization: "PVEAPIToken={{ proxmox_api_user }}!{{ proxmox_api_token_id }}={{ proxmox_api_token_secret }}"
        body_format: json
        body:
          enable: 1
        validate_certs: no
      register: proxmox_call

    - name: PRINT proxmox_call
      debug:
        var: proxmox_call

  ####
  ####

  when: proxmox_vm_action == "firewall_node_enable"
